name: dashboard
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

  # State Management
  get: ^4.6.5


  # Dependency Injection
  get_it: ^7.2.0


  # Fetch API
  dio: ^4.0.6
  http: ^0.13.4


  # Local Storage
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2


  # UI
  cupertino_icons: ^1.0.2  
  flutter_screenutil: ^5.5.3+2
  fluentui_system_icons: ^1.1.174
  flutter_offline: ^2.1.0
  lottie: ^1.3.0  
  cached_network_image: ^3.2.1


  # Date
  intl: ^0.17.0
  jiffy: ^5.0.0


  # TOOLS
  device_info_plus: ^0.0.1
  open_file: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true